# .github/release.yml

changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
        - Est
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - enhancement
        -Est
    - title: Other Changes
      labels:
        - "chnage01"
