on: pull_request

jobs:
  make_change:
    runs-on: ubuntu-latest
    outputs: 
      new-branch: ${{ steps.check.outputs.new-branch }}
    steps:
      - id: pull
        run: |
             pull_branch=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
             echo "Pull request Branch: $pull_branch"
             echo "::set-output name=pull_branch::$pull_branch"
             pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
             echo "Pull request Number: $pull_number"
             echo "::set-output name=pull_number::$pull_number"
      - uses: actions/checkout@v3
        with:
          ref: ${{ steps.pull.outputs.pull_branch}}
      - id: check
        run: |
          git config --global user.name 'GopikaV24'
          git config --global user.email 'gopika.vijayakumar@mnscorp.net'
          git clone https://github.com/Test-Spike/composite-actions.git
          cd composite-actions
          git checkout ${{ steps.pull.outputs.pull_branch}}
          git checkout -b branch-${{ steps.pull.outputs.pull_number}}
          echo "::set-output name=new-branch::branch-${{ steps.pull.outputs.pull_number}}"
          git status
          echo "***************Printing  mentioned places****************"
          grep -rn "@test-comp" *  
          echo "******************Replacing  with  in all action.yml files*******************"
          find ./ -type f -exec sed -i -e "s|@test-comp|@branch-${{ steps.pull.outputs.pull_number}}|g" {} \;
          #find ./workflows/ -type f -exec sed -i -e "s|@latest|@$new_tag|g" {} \;
          echo "Replacing  with  in all action.yml files"
          echo "******************After replacing new version, Printing  mentioned places**************************"
          grep -rn "@branch-${{ steps.pull.outputs.pull_number}}" *
          echo "*********************Pushing changes into the main branch***********************"
          git add .
          git commit -am "Replacing"
          git push origin branch-${{ steps.pull.outputs.pull_number}}


  hello_world_job:
    needs: [make_change]
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: pull
        run: |
             pull_branch=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
             echo "Pull request Branch: $pull_branch"
             echo "::set-output name=pull_branch::$pull_branch"
             pull_number=$(jq --raw-output .pull_request.head.ref "$GITHUB_EVENT_PATH")
             echo "Pull request Number: $pull_number"
             echo "::set-output name=pull_number::$pull_number"
      - uses: actions/checkout@v3
      - id: foo
        uses: Test-Spike/composite-actions@branch-18
        with:
          who-to-greet: 'Gopika'
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash
