name: Releases
on:
  push:
    branches:
      - main

jobs:
  changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
